accounts/urls.py
from django.conf.urls import url
from.import views


app_name= 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
    

]

articles/urls.py
from django.conf.urls import url
from django.contrib import admin
from.import views
app_name= "articles"
urlpatterns = [
    url(r'^$',views.article_list,name="list"),
    url(r'^create/$',views.article_create,name="create"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_details,name="details"),
    url(r'^category/(?P<slug>[\w-]+)/$', views.show_category, name='category'),
    url(r'^tag/(?P<tag_slug>[\w-]+)/$',views.article_list,name='post_list_by_tag'),






]

djangonautic/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from.import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^articles/',include('articles.urls')),
    url(r'^about/$',views.about),
    url(r'^$',views.homepage,name="home"),
    url(r'^like/$', article_views.like_post, name='like_post'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    #url(r'^category/(?P<hierarchy>.+)/$', article_views.show_category, name='category')

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from django.utils.text import slugify
from model_utils.fields import StatusField
from model_utils import Choices
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
User = get_user_model()

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(blank=True,null=True,)
    class Meta:
          #enforcing that there can not be two
        verbose_name_plural = "categories"       #categories under a parent with same
                                                 #slug

    def __str__(self):                           # __str__ method elaborated later in
       return self.name



    def get_absolute_url(self):
        return reverse("category", args=[self.name])



class Article(models.Model):
    STATUS =Choices('DRAFTS','PUBLISHED',)
    title = models.CharField(max_length=100)
    slug = models.SlugField(blank=True,null=True,)
    body= RichTextUploadingField()
    category = models.ForeignKey('Category', null=True, blank=True,on_delete=models.CASCADE,)
    date =models.DateTimeField(auto_now_add= True,)
    thumb =models.ImageField(default='default.jpg', blank=True,null=True,)
    author=models.ForeignKey(User,models.SET_NULL,null=True,blank=True,)
    likes=models.ManyToManyField(User,blank=True,related_name='post_likes',)
    tags=TaggableManager()
    status=StatusField(default="DRAFTS")
    class Meta:
        ordering = ['-date']
    def __unicode__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("articles:details", args=[self.slug])
    def total_likes(self):
        return self.likes.count()
    def __str__(self):
        return self.title


class Comment(models.Model):
    post=models.ForeignKey(Article,on_delete=models.CASCADE,null=True,)
    user=models.ForeignKey(User,models.SET_NULL,null=True,blank=True,)
    content=models.TextField()
    timestamp =models.DateTimeField(auto_now_add= True,)
    reply=models.ForeignKey('Comment',null=True ,on_delete=models.CASCADE,related_name="replies")

    def __str__(self):
        return '{}-{}' .format(self.post.title,str(self.user.username))

    class Meta:
        ordering = ['-id']

articles/forms.py
from django import forms

from .models import Article,Comment

class CreateArticle(forms.ModelForm):
    class Meta:
        model=Article
        fields=['title' ,'body','slug','thumb','tags' ]
class CommentForm(forms.ModelForm):
    content = forms.CharField(label="",widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'Leave a Comment...','rows':'2' ,}))
    class Meta:
        model=Comment
        fields=['content',]

articles/views.py
from django.http import HttpResponseRedirect,HttpResponse ,JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from .models import Article,Comment,Category

from django.urls import reverse
from django.db.models import Q
from .forms import *
from django.contrib.auth.decorators import login_required
from .import forms
from .forms import CommentForm
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import RedirectView
from django.template.loader import render_to_string
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth import get_user_model
User = get_user_model()
# Create your views here.
def article_list(request,tag_slug=None):
    article_list = Article.objects.all().filter(status="PUBLISHED")
    query= request.GET.get("q")
    categories=Category.objects.all()

    tag=None
    if query:
        article_list=article_list.filter(
        Q(title__icontains=query)|
        Q(author__username=query)|
        Q(body__icontains=query)
        ).distinct()
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        article_list=article_list.filter(tags__in=[tag],status="PUBLISHED")

    paginator = Paginator(article_list, 7)
    page =request.GET.get('page')
    try:
        articles=paginator.get_page(page)
    except PageNotInteger:
        articles=paginator.get_page(1)
    except EmptyPage:
        articles=paginator.get_page(paginator.num_pages)

    return render(request,'articles/article_list.html',{'articles':articles,'tag':tag,'categories':categories})

def article_details(request,slug):
    post=get_object_or_404(Article,slug=slug)
    categories=Category.objects.all()
    tag=Tag.objects.all()
    comments=Comment.objects.filter(post=post,reply= None)
    is_liked = False
    if post.likes.filter(id =request.user.id).exists():
        is_liked = True
    comment_form = CommentForm( )
    comment_qs =None

    post_tags_ids = post.tags.values_list('id', flat=True)

    similar_posts = Article.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags')[:6]
    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None )

        if comment_form.is_valid():
            content=request.POST.get('content')
            reply_id =request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs=Comment.objects.get(id=reply_id)

            comment=Comment.objects.create(post=post,user=request.user,content=content,reply=comment_qs)

            comment.save()
            print(comment)
            #comment_form.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form =CommentForm()
    return render(request,'articles/article_details.html',{'post_tags_ids':post_tags_ids,'articles':post,'tag': tag, 'categories':categories,'post':post,'comments':comments,'similar_posts':similar_posts,'comment_form':comment_form,'reply':comment_qs,'is_liked':is_liked,'total_likes':post.total_likes(),})

def like_post(request):
    post=get_object_or_404(Article,id=request.POST.get('post_id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request. user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    return HttpResponseRedirect(post.get_absolute_url())


    #return HttpResponseRedirect(post.get_absolute_url())


@login_required(login_url="/accounts/login")
def article_create(request):
    if request.method=='POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect('articles:list')
    else:
        form =forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})


def show_category(request,slug):
    categories=Category.objects.all()
    posts=Article.objects.all().filter(status="PUBLISHED")
    if slug:
        category=get_object_or_404(Category,slug=slug)
        posts=posts.filter(category=category)
    paginator = Paginator(posts, 6)
    page =request.GET.get('page')
    try:
        posts=paginator.get_page(page)
    except PageNotInteger:
        posts=paginator.get_page(1)
    except EmptyPage:
        posts=paginator.get_page(paginator.num_pages)

    return render(request,'articles/category.html',{'posts':posts,'category':category,'categories':categories,})

articles/templates/articles/article.html
 {% extends 'base.html'%}

{% block content %}
<div style="margin:80px;">
</div>
<div class="blog">
 <div class="container">
 <h1 class="text-center">Blog</h1>
 <div class="row">
 {% for article in articles %}
 
   <div class="col-md-4 col-lg-4 col-sm-12">
    <div class="card">
     <div class="card-img">
      <img src="{{article.thumb.url}}" class="img-fluid">
      <span><h4>{{article.category}}</h4></span>
     </div>
     <div class="card-footer">
      <small>Posted by : {{article.author.username}}</small>
     </div>
     
     <div class="card-body">
     <h4 class="card-title"><a href="{% url 'articles:details' article.pk %}"{{article.title}}</h4>
      <p class="card-text">
       {{article.body |truncatewords:20|safe }}
     </p>
    
    </p>
     </div>
     <div class="card-footer">
      <a href="{% url 'articles:details' article.pk %}" class="card-link">Read more</a>
     </div>
    </div>
   </div>


{% endfor %}
</div>
</div>
</div>
  {% if articles.has_other_pages %}

<ul class="pagination justify-content-center" style="margin:20px 0">
{% if articles.has_previous %}
  <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">&laquo;</a></li>
{% else %}
  <li class="page-item disabled"><a class="page-link" tabindex="-1">&laquo;</span></a></li>
{% endif %}
{% for i in articles.paginator.page_range %}
  {% if users.number == i %}
    <li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
  {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
{% endfor %}
{% if articles.has_next %}
  <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">&raquo;</a></li>
{% else %}
  <li class="page-item disabled"><a class="page-link" tabindex="-1"><span aria-hidden="true">&raquo;</span></a></li>
{% endif %}
</ul>

{% endif %}

{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base.html'%}




{% block content %}

 <div class="parallax-signup" data-parallax="scroll" data-z-index="1" style="background-image: url(/static/img/work-5.jpg)">
  <div clas="container">
    <br>
    <br>

      <h1 class="para-signup" style="margin-top: 45px; margin-left: 32%; color:green">Create An Awesome Article</h1>


      <form class="site-form-create"action ="{% url 'articles:create' %}"method="post"enctype="multipart/form-data">
        <h2 class="parralax-info">Create an Awesome Articles </h2>
        {% csrf_token %}
        {{ form.media }}
        {{form}}
        <a href="{% url 'home' %}" class="create"><button class="create" type="submit" name="button"  ">Cancel</button></a>
        <input type="submit" value="Create" >

      </form>


    </div>
  </div>
  <script src="/static/slugify.js"></script>
  <script src="/static/ckeditor.js"></script>



{% endblock %}

articles/templates/articles/article_details.html
{% extends 'base.html'%}

{% block content %}

  <!--/ Intro Skew Star /-->
  <div class="intro intro-single route bg-image" style="background-image: url(/static/img/overlay-bg.jpg)">
    <div class="overlay-mf"></div>
    <div class="intro-content display-table">
      <div class="table-cell">
        <div class="container">
          <br>
          <br>
          <h2 class="intro-title mb-4">{{articles.title}}</h2>

        </div>
      </div>
    </div>
  </div>

  <!--/ Intro Skew End /-->

  <!--/ Section Blog-Single Star /-->
  <section class="blog-wrapper sect-pt4" id="blog">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="post-box">
            <div class="post-thumb">
              <img src="{{articles.thumb.url}}" class="img-fluid" alt="">
            </div>
            <div class="post-meta">
              <h1 class="article-title">{{articles.title}}</h1>
              <ul>
                <li>
                  <span class="ion-ios-person"></span>
                  <a href="#">{{articles.author}}</a>
                </li>
                <li>
                 <span class="ion-pricetag"></span>

                {% for tag in post.tags.all %}
                  <a href="{% url 'articles:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% endfor %}
                </li>
                <li>
                  <span class="ion-chatbox"></span>
                  <a href="#">{{comments.count}}</a>
                </li>
                <li>
                  {% if request.user.is_authenticated %}
    <form action="{% url 'like_post' %}" method="post" class="like-btn">
      {% csrf_token %}
      {% if is_liked %}
        <button type="submit" id="like" name="post_id" value="{{ post.id }}">
        <i class="fa fa-heart" ></i> <a>{{total_likes}}</a>
      {% else %}
        <button type="submit" id="like" name="post_id" value="{{ post.id }}">
        <i class="fa fa-heart-o"></i> <a>{{total_likes}}</a>
      {% endif %}


    </form>

  {% endif %}
                </li>
              </ul>
            </div>
            <div class="article-content">

                {{articles.body}}

            </div>
          </div>
          <div class="box-comments">
            <div class="title-box-2">
              <h4 class="title-comments title-left">Comments ({{comments.count}})</h4>
            </div>
            <ul class="list-comments">
               {% for comment in comments %}
              <li>
                <div class="comment-avatar">
                  <img src="img/testimonial-2.jpg" alt="">
                </div>
                <div class="comment-details">
                  <h4 class="comment-author">{{comment.user}}</h4>
                  <span>{{comment.timestamp}}</span>
                  <p>
                    {{comment.content}}
                  </p>
                  <button  type="button"  id ="reply" class="reply-btn btn btn-outline-dark btn-sm" >Reply</button> |  {% if comment.replies.count <= 1 %}{{comment.replies.count}}Reply {% endif %}{% if comment.replies.count > 1 %}{{comment.replies.count}}Replies{% endif %}
                  <div class="replied-comments"  id ="reply-cmnt" style="display:None;">
                    <div class =" form-group ">
                      <form  class="comment" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="comment_id" value="{{ comment.id }}">
                        {{ comment_form.as_p }}
                        {% if request.user.is_authenticated  %}
                          <input type="submit" value="Reply" class="btn btn-outline-success">
                        {% else %}
                          <input type="submit" value="Reply" class="btn btn-outline-success" disabled>
                        {% endif %}
                    </form>
                  </div>
                  <h7><b>Replies</b></h7>
                  <div class="comment-details">
                  {% for reply in comment.replies.all %}

                    <h4 class="comment-author">{{reply.user|capfirst}}</h4>
                    <span>{{reply.timestamp}}</span>
                    <p>
                      {{reply.content}}
                    </p>


                {% endfor %}
                  </div>
              </div>
            </div>
          </li>
              {% endfor %}
            </ul>
          </div>
          <div class="form-comments">
            <div class="title-box-2">
              <h3 class="title-left">
                Leave a Reply
              </h3>
            </div>
            <form class="form-mf">
              <div class="row">
                <div class="col-md-12 mb-3">
                  <div class="form-group">
                    {% csrf_token %}
                    {{comment_form}}
                  </div>
                </div>
                <div class="col-md-12">
                  {% if request.user.is_authenticated %}
                    <button type="submit" value="Comment" class="button button-a button-big button-rouded ">Submit</button>
                  {% else %}
                    <button type="submit" value="Comment" class="button button-a button-big button-rouded" disabled>Submit</button >
                  {% endif %}

                </div>
              </div>
            </form>
          </div>
        </div>
        <div class="col-md-4">
          <div class="widget-sidebar sidebar-search">
            <h5 class="sidebar-title">Search</h5>
            <div class="sidebar-content">
              <form method="GET">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for..." aria-label="Search for..." name='q'>
                  <span class="input-group-btn">
                    <button class="btn btn-secondary btn-search" type="submit">
                      <span class="ion-android-search"></span>
                    </button>
                  </span>
                </div>
              </form>
            </div>
          </div>
          <div class="widget-sidebar">
            <h5 class="sidebar-title">Simillar Post</h5>
            <div class="sidebar-content">
              <ul class="list-sidebar">
                {% for post in similar_posts %}
                <li>
                  <a href="{% url 'articles:details' post.slug %}">{{post.title}}</a>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>

          <div class="widget-sidebar widget-tags">
            <h5 class="sidebar-title">Tags</h5>
            <div class="sidebar-content">
              <ul>
                {% for tags in tag %}
                <li>
                  <a href="{% url 'articles:post_list_by_tag' tags.slug %}">{{tags.name}}</a>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ Section Blog-Single End /-->

<!--
        {% for comment in comments %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.user}}</h5>
            {{comment.content}}
            <br>
             <small> <button  type="button"  id ="reply" class="reply-btn btn btn-primary btn-sm" >Reply</button> |  {% if comment.replies.count <= 1 %}{{comment.replies.count}}Reply {% endif %}{% if comment.replies.count > 1 %}{{comment.replies.count}}Replies{% endif %}
            </small>




              <div class="replied-comments"  id ="reply-cmnt" style="display: none" >


                  <div class =" form-group ">
                  <form  class="comment" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="comment_id" value="{{ comment.id }}">
                    {{ comment_form.as_p }}
                    {% if request.user.is_authenticated  %}
                      <button ype="submit" value="Reply" class="btn btn-primary btn-sm">Reply</button>
                    {% else %}
                      <button type="submit" value="Reply" class="btn btn-primary btn-sm" disabled>Reply</button>
                    {% endif %}
                  </form>
                </div>


            {% for reply in comment.replies.all %}
            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">{{reply.user|capfirst}}</h5>
                {{reply.content}}
              </div>
            </div>
            {% endfor %}

          </div>
          </div>
        </div>
          {% endfor %}
        </div>

-->


{% endblock %}

articles/templates/articles/article_details0.html
{% extends 'base.html'%}

{% block content %}



<div class="my-parallax" data-parallax="scroll" data-z-index="1" data-image-src="{{articles.thumb.url}}">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">



 
            <div class="post-heading">
              <h1>{{articles.title}}</h1>
              <span class="meta">Posted by
                {{articles.author}}
                on {{articles.date}}</span>


          </div>
        </div>
      </div>
    </div> 
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-md-10 mx-auto">
      <section class="section section-light">
        <p>
       


              {{articles.body| safe}}

        </p>
      </section>
    </div>
  </div>
<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
   <div class="article">
                    <h2><a href="{% url 'articles:details' post.pk %}">{{.title}}</a></h2>
                    <h3 class="post-subtitle">{{article.snippet}}</h3>
                    <p class ="post-date">Posted by {{article.author}}
                      on {{article.date}}
                  category: <a href="{%url 'articles:category' post.category.pk %}">{{article.category}} </a>
                   Tags:
                  {% for tag in article.tags.all %}
                  <a href="{% url 'articles:post_list_by_tag' tag.slug %}">
                  {{ tag.name }}
                  </a>
                  {% if not forloop.last %}, {% endif %}
                  {% endfor %}

                 </p>
                  </div>
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}


  {% include 'articles/like_section.html' %}
 



  <div class="row">
    <div class="col-lg-10 col-md-10 mx-auto">
      <section class="comment-like">  
        <h3 class = "site-heading" align = "left-top ">Leave a Comment</h3>
          <hr>
            <div class="form-group ">
                <form class="comment"  method="POST">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    {% if request.user.is_authenticated  %}
                      <input type="submit" value="Comment" class="btn btn-outline-success">
                    {% else %}
                      <input type="submit" value="Comment" class="btn btn-outline-success" disabled>
                    {% endif %}
                </form>
            </div>
      </section>
    </div>
  </div>

 
  <div class="row">
    <div class="col-lg-10 col-md-10 mx-auto">
      <section class="section section-light">  



    {% for comment in comments %}
     

      <blockquote class="blockquote">  <i class="fa fa-user"></i>  <cite title="Source Title">{{comment.user}}</cite>
        <blockquote class="blockquote-footer"><cite title="Source Title"> <small> {{comment.content}}</small></cite>
      <button  type="button"  id ="reply" class="reply-btn btn btn-outline-dark btn-sm" >Reply</button> |  {% if comment.replies.count <= 1 %}{{comment.replies.count}}Reply {% endif %}{% if comment.replies.count > 1 %}{{comment.replies.count}}Replies{% endif %}
       </blockquote>
        


    <div class="replied-comments"  id ="reply-cmnt" style="display: none;">   
      

    <div class =" form-group ">
      <form  class="comment" method="POST">
        {% csrf_token %}
        <input type="hidden" name="comment_id" value="{{ comment.id }}">
        {{ comment_form.as_p }}
        {% if request.user.is_authenticated  %}
          <input type="submit" value="Reply" class="btn btn-outline-success">
        {% else %}
          <input type="submit" value="Reply" class="btn btn-outline-success" disabled>
        {% endif %}
      </form>
    </div>
     <h7><b>Replies</b></h7>  
     {% for reply in comment.replies.all %}
    <blockquote class="blockquote">  <i class="fa fa-user"></i>  <cite title="Source Title">{{reply.user|capfirst}}</cite>
      <blockquote class="blockquote-footer"><small><cite title="Source Title">  {{reply.content}}</cite></small> </blockquote>
    </blockquote>
    {% endfor %}
  </div>
   </blockquote>
    {% endfor %}
  
    </section> 
  </div>
  </div>
</div>




<script src="/static/bootstrap.js"></script>

<script src ="/static/bootstrap.min.js"></script>




{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base.html'%}

{% block content %}
<div class="intro intro-single route bg-image" style="background-image: url(/static/img/overlay-bg.jpg)">
   <div class="overlay-mf"></div>
   <div class="intro-content display-table">
     <div class="table-cell">
       <div class="container">
         <br>
         <br>
         <h2 class="intro-title mb-4">Blogs on Tag {{tag.name}}</h2>

       </div>
     </div>
   </div>
 </div>
<main class="mt-5 pt-5">
   <div class="container">


     <!--Section: Cards-->
     <section class="pt-5" style="margin-top: -60px;">

       {% for post in articles %}

       <hr class="mb-5">

       <!--Grid row-->
       <div class="row wow fadeIn">

         <!--Grid column-->
         <div class="col-lg-5 col-xl-4 mb-4">
           <!--Featured image-->
           <div class="view overlay rounded z-depth-1">
             <img src="{{post.thumb.url}}" class="img-fluid" alt="" style="width:400px; height:200px;">

               <div class="mask rgba-white-slight"></div>

           </div>
         </div>
         <!--Grid column-->

         <!--Grid column-->
         <div class="col-lg-7 col-xl-7 ml-xl-4 mb-4">
           <h3 class="mb-3 font-weight-bold dark-grey-text">
             <strong>{{post.title}}</strong>
           </h3>
           <p class="grey-text">  {{post.body |truncatewords:20|safe }}</p>
           <a href="{% url 'articles:details' post.slug %}" target="_blank" class="btn btn-primary btn-md">Read More

             <i class="fa fa-play ml-2"></i>
           </a>
         </div>
       </div>
       
         {% empty %}
         <center><h1>Coming Soon....</h1></center>
      <!--Grid column-->
         {% endfor %}

   </section>
 </div>
</main>


{% if articles.has_other_pages %}

<ul class="pagination justify-content-center" style="margin:20px 0">
{% if articles.has_previous %}
 <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">&laquo;</a></li>
{% else %}
 <li class="page-item disabled"><a class="page-link" tabindex="-1"><span aria-hidden="true">&laquo;</span></a></li>
{% endif %}
{% for i in articles.paginator.page_range %}
 {% if users.number == i %}
   <li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
 {% else %}
   <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
 {% endif %}
{% endfor %}
{% if articles.has_next %}
 <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">&raquo;</a></li>
{% else %}
 <li class="page-item disabled"><a class="page-link" tabindex="-1"><span aria-hidden="true">&raquo;</span></a></li>
{% endif %}
</ul>

{% endif %}


{% endblock %}

articles/templates/articles/category.html
 {% extends 'base.html'%}

{% block content %}
<div class="intro intro-single route bg-image" style="background-image: url(/static/img/overlay-bg.jpg)">
    <div class="overlay-mf"></div>
    <div class="intro-content display-table">
      <div class="table-cell">
        <div class="container">
          <br>
          <br>
          <h2 class="intro-title mb-4">Blogs on {{category.name}}</h2>

        </div>
      </div>
    </div>
  </div>
 <main class="mt-5 pt-5">
    <div class="container">


      <!--Section: Cards-->
      <section class="pt-5" style="margin-top: -60px;">

        {% for post in posts %}

        <hr class="mb-5">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-lg-5 col-xl-4 mb-4">
            <!--Featured image-->
            <div class="view overlay rounded z-depth-1">
              <img src="{{post.thumb.url}}" class="img-fluid" alt="" style="width:400px; height:200px;">

                <div class="mask rgba-white-slight"></div>

            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-7 col-xl-7 ml-xl-4 mb-4">
            <h3 class="mb-3 font-weight-bold dark-grey-text">
              <strong>{{post.title}}</strong>
            </h3>
            <p class="grey-text">  {{post.body |truncatewords:20|safe }}</p>
            <a href="{% url 'articles:details' post.slug %}" target="_self" class="btn btn-primary btn-md">Read More

              <i class="fa fa-play ml-2"></i>
            </a>
          </div>
          </div>
          {% empty %}
          <center><h1>Coming Soon....</h1></center>

          <!--Grid column-->
          {% endfor %}

    </section>
  </div>
</main>


 {% if posts.has_other_pages %}

<ul class="pagination justify-content-center" style="margin:20px 0">
{% if posts.has_previous %}
  <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
{% else %}
  <li class="page-item disabled"><a class="page-link" tabindex="-1">&laquo;</span></a></li>
{% endif %}
{% for i in posts.paginator.page_range %}
  {% if users.number == i %}
    <li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
  {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
{% endfor %}
{% if posts.has_next %}
  <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">&raquo;</a></li>
{% else %}
  <li class="page-item disabled"><a class="page-link" tabindex="-1"><span aria-hidden="true">&raquo;</span></a></li>
{% endif %}
</ul>

{% endif %}


{% endblock %}