accounts/urls.py
from django.conf.urls import url
from.import views


app_name= 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
    

]

articles/urls.py
from django.conf.urls import url
from django.contrib import admin
from.import views
app_name= "articles"
urlpatterns = [
    url(r'^$',views.article_list,name="list"),
    url(r'^create/$',views.article_create,name="create"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_details,name="details"),
    url(r'^category/(?P<slug>[\w-]+)/$', views.show_category, name='category'),
    url(r'^tag/(?P<tag_slug>[\w-]+)/$',views.article_list,name='post_list_by_tag'),






]

djangonautic/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from.import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^articles/',include('articles.urls')),
    url(r'^about/$',views.about),
    url(r'^$',views.homepage,name="home"),
    url(r'^like/$', article_views.like_post, name='like_post'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    #url(r'^category/(?P<hierarchy>.+)/$', article_views.show_category, name='category')

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Technohub</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">


  <!-- Favicons -->
  <!--<link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">
-->
  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">


   <script type="text/javascript">
        $(document).ready(function(event){
          $(".reply-btn").click(function(event){
              $(this).next(".replied-comments").toggle();
          });
         });
      </script>
</head>

<body id="page-top">

  <!--/ Nav Star /-->
  <nav   class="navbar navbar-b navbar-trans navbar-expand-md fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll" href="{% url 'home' %}">TechnoHub</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault"
        aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll active" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll" href="{% url 'home' %}#about">About</a>
          </li>

          <li class="nav-item">
            <a class="nav-link js-scroll" href="{% url 'home' %}#team">Team</a>
          </li>
          <li class="nav-item">
            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle " id="navbarDropdownMenuLink" data-value="blogs_info" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false" href="">Blogs</a>
        </a>
        <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink">
          {% for category in categories %}
          <a class="dropdown-item" href="{% url 'articles:category' category.slug %}">{{category.name}}</a>
          {% endfor %}

        </div>
      </li>

          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll" href="{% url 'home' %}#contact">Contact</a>
          </li>



        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Register</a>
        </li>
        {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
            <i class="fa fa-user" style="margin-right: 5px;"></i>Hello  {{ request.user.username}}
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="navbarDropdownMenuLink">

          <a class="dropdown-item">
            <form classs="logout_link" action ="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type ="submit" class="btn btn-link navbar-btn">Logout</button>
             </form>
          </a>


          <a class="dropdown-item" href="{% url 'articles:create' %}">create Article</a>

        </div>
      </li>
      {% endif %}



      </ul>
    </div>
  </div>
</nav>
  <!--/ Nav End /-->




    <!--Navbar-->

<!--Navbar -->
            {% block content %}

          {% endblock %}

 <section class="paralax-mf footer-paralax bg-image sect-mt4 route" style="background-image: url(/static/img/overlay-bg.jpg)">
    <footer>
      <div class="overlay-mf"></div>
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="copyright-box">
              <p class="copyright">&copy; Copyright <strong>TechnoHub</strong>. All Rights Reserved</p>
              <div class="credits">
                <!--
                  All the links in the footer should remain intact.
                  You can delete the links only if you purchased the pro version.
                  Licensing information: https://bootstrapmade.com/license/
                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=DevFolio
                -->
                Designed by <a href="#">TechnoHub</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </section>


  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <div id="preloader"></div>

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'lib/popper/popper.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'lib/counterup/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'lib/counterup/jquery.counterup.js' %}"></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
  <script src="{% static 'lib/typed/typed.min.js' %}"></script>
  <!-- Contact Form JavaScript File -->
  <script src="{% static 'contactform/contactform.js' %}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}"></script>

  </body>
</html>

templates/base0.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang ="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0 ,shrink-to-fit=no">
      <link rel ="stylesheet" href="{% static 'bootstrap.min.css' %}" >
      <link rel ="stylesheet" href="{% static 'font-awesome.4.7.css' %}" >




      <script src="{% static 'jquery.min.js' %}"></script>

     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
     
      <script src="{% static 'parallax.min.js' %}"></script>
      <script type="text/javascript">
        $(document).ready(function(event){
          $(".reply-btn").click(function(event){
              $(this).parent().next(".replied-comments").toggle();
          });
         }); 
      </script>
      <title>Article</title>
      </head>
   <body>
   <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
         <a class ="navbar-brand" href="{% url 'home'%}"><b><i>TechnoHub</b></i></a>
       </div>
       
 
                <div class="collapse navbar-collapse" id="mynavbar">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>   <a class="navbar-brand">Hello {{ request.user}} </a></li>
                  <li><form classs="logout_link" action ="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token%}
                    <button type ="submit" class="btn btn-default navbar-btn">Logout</button>
                  </form>
                  </li>
                  <li><a href="{% url 'articles:create' %}">New article</a></li>
                {% else %}
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            
            <li> <form class="form-inline" method="GET">
      <input class="form-control" type="search" placeholder="Search.." name='q'>
      <button class="btn btn-outline-sucess" id="find" type="submit"><i class="fa fa-search"></i></button>
    </form></li></ul>
  
          </div>
      </div>
    </nav>

            {% block content %}

          {% endblock %}

          <footer class="text-muted" border-top="1px">
            <div class="footer-social-icons">
      <h4 class="follow">Follow us on</h4>
      <ul class="social-icons">
          <li><a href="" class="social-icon"> <i class="fa fa-facebook"></i></a></li>
          <li><a href="" class="social-icon"> <i class="fa fa-twitter"></i></a></li>
          <li><a href="" class="social-icon"> <i class="fa fa-rss"></i></a></li>
          <li><a href="" class="social-icon"> <i class="fa fa-youtube"></i></a></li>
          <li><a href="" class="social-icon"> <i class="fa fa-linkedin"></i></a></li>
          <li><a href="" class="social-icon"> <i class="fa fa-google-plus"></i></a></li>
      </ul>
  </div>
        <div class="container">
        <p align= "right">
          <a href="#">Back to top</a>
        </p>
        <p>TechnoHub &copy; 2017-2018</p>
        <p><a href="../../">Visit the homepage</a></p>
       </div>
          </footer>

          <script src ="{% static 'bootstrap.min.js' %}"></script>
           <script src ="{% static 'bootstrap.js' %}"></script>
           <script src="https://code.jquery.com/jquery-1.10.2.js"></script>

          
  </body>
</html>

templates/home.html
 {% extends 'base.html'%}
{% load static from staticfiles %}

{% block content %}



  <div id="home" class="intro route bg-image" style="background-image: url({% static 'img/My Post.jpg' %})">
    <div class="overlay-itro"></div>
    <div class="intro-content display-table">
      <div class="table-cell">
        <div class="container">

          <h1 class="intro-title mb-4">Welcome to Technohub </h1>
          <p class="intro-subtitle"><span class="text-slider-items">Website For Latest News  on Technology,Website For Latest News  on upcoming languages</span><strong class="text-slider"></strong></p>

        </div>

      </div>
    </div>
  </div>
  <section id="about" class="about-mf sect-pt4 route">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="box-shadow-full">
            <div class="row">
              <div class="col-md-6">
                <div class="row">
                </div>
                <div class="skill-mf">
                  <p class="title-s">Categories</p>
                  <span>Trending Technology</span> <span class="pull-right">85%</span>
                  <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 85%;" aria-valuenow="85" aria-valuemin="0"
                      aria-valuemax="100"></div>
                  </div>
                  <span>Latest Tech News</span> <span class="pull-right">75%</span>
                  <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0"
                      aria-valuemax="100"></div>
                  </div>
                  <span>Trending Programming Languages</span> <span class="pull-right">50%</span>
                  <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                      aria-valuemax="100"></div>
                  </div>
                  <span>Competitive Exam Subjects</span> <span class="pull-right">50%</span>
                  <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                      aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="about-me pt-4 pt-md-0">
                  <div class="title-box-2">
                    <h5 class="title-left">
                      About Us
                    </h5>
                  </div>
                  <p class="lead">
                    Technohub is an indigenous platform which strives to provide knowledge about the latest technologies reforms occuring day by day worldwide. We provide a bunch of exploration about the latest technological assets, researches and higher development applications. We are catering to improve the skills of techy readers and to update them about the various technologies.
In India, there are a huge number of institutions which are waking up the communities for higher studies and research. A lot of professionals are striving to pool their advanced minds but many of them can't find a right stage to exhibit their sharp skills.
So, here at Technohub, we provide you the right platform to brush up your mind about the technologies and to stay updated with the latest news of the techno-world. Backed by a team of experienced professionals, it will be our assiduous effort to convert you into a veteran from a newbie.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <div class="testimonials paralax-mf bg-image" style="background-image: url(img/overlay-bg.jpg)" id="team">
    <div class="overlay-mf"></div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div id="testimonial-mf" class="owl-carousel owl-theme">
            <div class="testimonial-box">
              <div class="author-test">
                <img src="/static/nitish.jpeg" alt="" class="rounded-circle b-shadow-a" style="height: 150px; width:150px; ">
                <span class="author">Nitish Gulia</span>
              </div>
              <div class="content-test">
                <p class="description lead">
                  Frontend & Backend Developer
                </p>
                <span class="comit"><i class="fa fa-quote-right"></i></span>
              </div>
            </div>
             <div class="testimonial-box">
              <div class="author-test">
                <img src="/static/surbhi.jpeg" alt="" class="rounded-circle b-shadow-a" style="height: 150px; width:150px; ">
                <span class="author">Surbhi Suman</span>
              </div>
              <div class="content-test">
                <p class="description lead">
                  Frontend & Backend Developer
                </p>
                <span class="comit"><i class="fa fa-quote-right"></i></span>
              </div>
            </div>
            <div class="testimonial-box">
              <div class="author-test">
                <img src="/static/nitish.jpeg" alt="" class="rounded-circle b-shadow-a" style="height: 150px; width:150px;" >
                <span class="author">Unknown</span>
              </div>
              <div class="content-test">
                <p class="description lead">
                  Blog Writer
                </p>
                <span class="comit"><i class="fa fa-quote-right"></i></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <section id="blog" class="blog-mf sect-pt4 route">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="title-box text-center">
            <h3 class="title-a">
              Blog
            </h3>
            <p class="subtitle-a">
            </p>
            <div class="line-mf"></div>
          </div>
        </div>
      </div>
      <div class="row">
        {% for article in articles %}

        <div class="col-md-4">
          <div class="card card-blog">
            <div class="card-img">
              <img src="{{article.thumb.url}}" alt="" class="img-fluid" style="height:200px; width:400px;">
            </div>
            <div class="card-body">
              <div class="card-category-box">
                <div class="card-category">
                  <h6 class="category">{{article.category}}</h6>
                </div>
              </div>
              <h3 class="card-title"><a href="{% url 'articles:details' article.slug %}">{{article.title}}</a></h3>
              <p class="card-description">
                 {{article.body |truncatewords:12|safe }}
              </p>
            </div>
            <div class="card-footer">
              <div class="post-author">
                <a href="#">
                  <i class="fa fa-user"></i>
                  <span class="author">{{article.author}}</span>
                </a>
              </div>
              <div class="post-date">
                <span class="ion-ios-clock-outline"></span> {{article.date}}
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>





<section class="paralax-mf footer-paralax bg-image sect-mt4 route" style="background-image: url(/static/img/overlay-bg.jpg)">
    <div class="overlay-mf"></div>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="contact-mf">
            <div id="contact" class="box-shadow-full">
              <div class="row">
                <div class="col-md-6">
                  <div class="title-box-2">
                    <h5 class="title-left">
                      Send Message Us
                    </h5>
                  </div>
                  <div>
                      <form action="" method="post" role="form" class="contactForm">

                      <div class="row">


                        <div class="col-md-12 mb-3">
                          <div class="form-group">
                             <form method="POST">

                              {% csrf_token %}
                              {{form.as_p}}

                          </div>
                        </div>

                        <div class="col-md-12">
                          <button type="submit" class="button button-a button-big button-rouded">Send Message</button>
                        </div>
                      </form>
                      </div>
                    </form>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="title-box-2 pt-4 pt-md-0">
                    <h5 class="title-left">
                      Get in Touch
                    </h5>
                  </div>
                  <div class="more-info">
                    <p class="lead">
                    </p>
                    <ul class="list-ico">
                      <li><span class="ion-ios-location"></span>New Delhi, India</li>
                      <li><span class="ion-ios-telephone"></span> +918285401666</li>
                      <li><span class="ion-email"></span> technohub@gmail.com</li>
                    </ul>
                  </div>
                  <div class="socials">
                    <ul>
                      <li><a href=""><span class="ico-circle"><i class="ion-social-facebook"></i></span></a></li>
                      <li><a href=""><span class="ico-circle"><i class="ion-social-instagram"></i></span></a></li>
                      <li><a href=""><span class="ico-circle"><i class="ion-social-twitter"></i></span></a></li>
                      <li><a href=""><span class="ico-circle"><i class="ion-social-pinterest"></i></span></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}